<a href="https://colab.research.google.com/github/TraeDWill/Dataeng_class/blob/main/Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
from urllib.request import urlopen
from bs4 import BeautifulSoup
import re
from pylab import rcParams

url = "https://www.hubertiming.com/results/2023WyEasterLong"
html = urlopen(url)
soup = BeautifulSoup(html, 'lxml')
type(soup)
title = soup.title
print(title)
text = soup.get_text()
print(soup.text)
soup.find_all('a')
all_links = soup.find_all("a")
for link in all_links:
    print(link.get("href"))
    rows = soup.find_all('tr')
print(rows[:10])
for row in rows:
    row_td = row.find_all('td')
print(row_td)
type(row_td)
list_rows = []
for row in rows:
    cells = row.find_all('td')
    str_cells = str(cells)
    clean = re.compile('<.*?>')
    clean2 = (re.sub(clean, '',str_cells))
    list_rows.append(clean2)
print(clean2)
type(clean2)

<title>Race results for the 2023 Wy'Easter Skimo Race!</title>







Race results for the 2023 Wy'Easter Skimo Race!





















 2023 Wy'easter Skimo Long - Open
 Government Camp, Mt Hood, OR
 March 26th, 2023



 Snowgoat Skimo






 Email
                        timing@hubertiming.com with results questions. Please include your bib number if you have it.









Huber Timing Home





Long - Open:


Finishers:
18


Male:
11


Female:
6


Non-Binary:
1







  Race Photos from Teresa Dalsager



 Vertical - Open
 Vertical - Heavy Mettle
 Long - Open
 Long - Heavy Mettle
 Long - Splitmo
 Recreation - Open
 Summary







Long - Open Results



Search:

Search
Division:

Men
Women
Non-Binary
Masters Men
Masters Women
Masters Non-Binary
F 25-29
F 35-39
F 40-44
M 25-29
M 30-34
M 35-39
M 40-44
M 45-49
M 55-59
O 30-34
 Filter




Place
Bib
Name
Gender
Age
City
State
Time
Gender Place
Age Group
Age Group Place




1
345


                    ZACH VIOLETT


M
40
BEND
OR
1:33:19


                    1 of 11


M 40-44


                    1 of 2




2
335


                    KYLEE ROOD


O
34
BEND
OR
1:42:56


                    1 of 1


O 30-34


                    1 of 1




3
323


                    ZEBEDIAH MILLSLAGL


M
25
BEND
OR
1:52:07


                    2 of 11


M 25-29


                    1 of 2




4
308


                    DAVID GRIFFIN


M
35
SEATTLE
WA
1:53:10


                    3 of 11


M 35-39


                    1 of 2




5
326


                    ADAM NILSEN


M
30
PORTLAND
OR
1:54:57


                    4 of 11


M 30-34


                    1 of 2




6
293


                    KAITLIN ALLEN


F
36
BEND
OR
1:56:01


                    1 of 6


F 35-39


                    1 of 2




7
362


                    GEORGE REYNYA


M
47
REDMOND
WA
2:05:40


                    5 of 11


M 45-49


                    1 of 2




8
305


                    ELY GERBIN


M
33
ISSAQUAH
WA
2:07:17


                    6 of 11


M 30-34


                    2 of 2




9
509


                    JOHN AMMONDSON


M
29
PORTLAND
OR
2:08:22


                    7 of 11


M 25-29


                    2 of 2




10
307


                    TYLER GREEN


M
39
PORTLAND
OR
2:09:02


                    8 of 11


M 35-39


                    2 of 2




11
297


                    MICHELLE BUNCKE


F
27
PORTLAND
OR
2:10:01


                    2 of 6


F 25-29


                    1 of 2




12
329


                    DAN PACKMAN


M
58
BEND
OR
2:10:38


                    9 of 11


M 55-59


                    1 of 1




13
328


                    BETH ANN ORTON


F
41
BEND
OR
2:18:33


                    3 of 6


F 40-44


                    1 of 2




14
339


                    AURA SPANN


F
38
WILLIAMS
OR
2:42:29


                    4 of 6


F 35-39


                    2 of 2




15
306


                    LISA GREEN


F
42
SNOQUALMIE PASS
WA
2:46:26


                    5 of 6


F 40-44


                    2 of 2




16
346


                    STEFFEN WEEBER


M
44
PORTLAND
OR
3:02:23


                    10 of 11


M 40-44


                    2 of 2




17
318


                    GREG LULOF


M
46
SEATTLE
WA
3:05:25


                    11 of 11


M 45-49


                    2 of 2




18
338


                    OLIVIA SPADOLA


F
27
PORTLAND
OR
3:27:28


                    6 of 6


F 25-29


                    2 of 2

















Huber Timing


Dark Mode






https://www.snowgoatskimo.com/
mailto:timing@hubertiming.com
https://www.hubertiming.com
https://photos.google.com/share/AF1QipOH1NdRAy6eTU48sA9TjVQm8TtfJdINxX2YFsfvrM0NvHZYi76cLSTJO-A0H87fcQ?key=UnMzVnlKUG9BZF9rdk1zS21EVVI5dlU5VVBhNmdB
https://www.teresadalsager.com/
/results/2023WyEaster
/results/2023WyEasterVertHM
/results/2023WyEasterLongHM
/results/2023WyEasterLongSplitmo
/results/2023WyEasterShort
/results/summary/2023WyEasterLong
None
#tabs-1
https://www.hubertiming.com/
https://facebook.com/hubertiming/
None
[<tr colspan="2">
<b>Long - Open:</b>
</tr>, <tr>
<td>Finishers:</td>
<td>18</td>
</tr>, <tr>
<td>Male:</td>
<td>11</td>
</tr>, <tr>
<td>Female:</td>
<td>6</td>
</tr>, <tr>
<td>Non-Binary:</td>
<td>1</td>
</tr>, <tr class="header">
<th>Place</th>
<th>Bib</th>
<th>Name</th>
<th>Gender</th>
<th>Age</th>
<th>City</th>
<th>State</th>
<th>Time</th>
<th>Gender Place</th>
<th>Age Group</th>
<th>Age Group Place</th>
</tr>, <tr data-bib="345">
<td>1</td>
<td>345</td>
<td>

                    ZACH VIOLETT

                </td>
<td>M</td>
<td>40</td>
<td>BEND</td>
<td>OR</td>
<td>1:33:19</td>
<td>

                    1 of 11

                </td>
<td>M 40-44</td>
<td>

                    1 of 2

                </td>
</tr>, <tr data-bib="335">
<td>2</td>
<td>335</td>
<td>

                    KYLEE ROOD

                </td>
<td>O</td>
<td>34</td>
<td>BEND</td>
<td>OR</td>
<td>1:42:56</td>
<td>

                    1 of 1

                </td>
<td>O 30-34</td>
<td>

                    1 of 1

                </td>
</tr>, <tr data-bib="323">
<td>3</td>
<td>323</td>
<td>

                    ZEBEDIAH MILLSLAGL

                </td>
<td>M</td>
<td>25</td>
<td>BEND</td>
<td>OR</td>
<td>1:52:07</td>
<td>

                    2 of 11

                </td>
<td>M 25-29</td>
<td>

                    1 of 2

                </td>
</tr>, <tr data-bib="308">
<td>4</td>
<td>308</td>
<td>

                    DAVID GRIFFIN

                </td>
<td>M</td>
<td>35</td>
<td>SEATTLE</td>
<td>WA</td>
<td>1:53:10</td>
<td>

                    3 of 11

                </td>
<td>M 35-39</td>
<td>

                    1 of 2

                </td>
</tr>]
[<td>18</td>, <td>338</td>, <td>

                    OLIVIA SPADOLA

                </td>, <td>F</td>, <td>27</td>, <td>PORTLAND</td>, <td>OR</td>, <td>3:27:28</td>, <td>

                    6 of 6

                </td>, <td>F 25-29</td>, <td>

                    2 of 2

                </td>]
[18, 338,

                    OLIVIA SPADOLA

                , F, 27, PORTLAND, OR, 3:27:28,

                    6 of 6

                , F 25-29,

                    2 of 2

                ]

str

In [ ]:
df = pd.DataFrame(list_rows)
df.head(10)

df1 = df[0].str.split(',', expand=True)
df1.head(10)

df1[0] = df1[0].str.strip('[')
df1.head(10)

col_labels = soup.find_all('th')

all_header = []
col_str = str(col_labels)
cleantext2 = BeautifulSoup(col_str, "lxml").get_text()
all_header.append(cleantext2)
print(all_header)

df2 = pd.DataFrame(all_header)
df2.head()

df3 = df2[0].str.split(',', expand=True)
df3.head()
frames = [df3, df1]

df4 = pd.concat(frames)
df4.head(10)
df5 = df4.rename(columns=df4.iloc[0])
df5.head()
df5.info()
df5.shape
df6 = df5.dropna(axis=0, how='any')
df6.info()
df6.shape
df7 = df6.drop(df6.index[0])
df7.head()

df7.rename(columns={'[Place': 'Place'},inplace=True)
df7.rename(columns={' Team]': 'Team'},inplace=True)
df7.head()

df7['Team'] = df7['Team'].str.strip(']')
df7.head()

['[Place, Bib, Name, Gender, Age, City, State, Time, Gender Place, Age Group, Age Group Place]']
<class 'pandas.core.frame.DataFrame'>
Index: 25 entries, 0 to 23
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   [Place             25 non-null     object
 1    Bib               23 non-null     object
 2    Name              19 non-null     object
 3    Gender            19 non-null     object
 4    Age               19 non-null     object
 5    City              19 non-null     object
 6    State             19 non-null     object
 7    Time              19 non-null     object
 8    Gender Place      19 non-null     object
 9    Age Group         19 non-null     object
 10   Age Group Place]  19 non-null     object
dtypes: object(11)
memory usage: 2.3+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 19 entries, 0 to 23
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   [Place             19 non-null     object
 1    Bib               19 non-null     object
 2    Name              19 non-null     object
 3    Gender            19 non-null     object
 4    Age               19 non-null     object
 5    City              19 non-null     object
 6    State             19 non-null     object
 7    Time              19 non-null     object
 8    Gender Place      19 non-null     object
 9    Age Group         19 non-null     object
 10   Age Group Place]  19 non-null     object
dtypes: object(11)
memory usage: 1.8+ KB

KeyError: 'Team'

In [ ]:
time_list = df7[' Gun Time'].tolist()
time_mins = []
for i in time_list:
    if(len(i.split(':')) == 3):
      h, m, s = i.split(':')
      math = (int(h) * 3600 + int(m) * 60 + int(s))/60
      time_mins.append(math)
    else:
      m, s = i.split(':')
      math = (int(m) * 60 + int(s))
      time_mins.append(math)
#print(time_mins)
df7['Runner_mins'] = time_mins
df7.head()
df7.describe(include=[np.number])
rcParams['figure.figsize'] = 15, 5


df7.boxplot(column='Runner_mins')
plt.grid(True, axis='y')
plt.ylabel('Chip Time')
plt.xticks([1], ['Runners'])

x = df7['Runner_mins']
ax = sns.distplot(x, hist=True, kde=True, rug=False, color='m', bins=25, hist_kws={'edgecolor':'black'})
plt.show()

f_fuko = df7.loc[df7[' Gender']==' F']['Runner_mins']
m_fuko = df7.loc[df7[' Gender']==' M']['Runner_mins']
sns.distplot(f_fuko, hist=True, kde=True, rug=False, hist_kws={'edgecolor':'black'}, label='Female')
sns.distplot(m_fuko, hist=False, kde=True, rug=False, hist_kws={'edgecolor':'black'}, label='Male')
plt.legend()

g_stats = df7.groupby(" Gender", as_index=True).describe()
print(g_stats)

df7.boxplot(column='Runner_mins', by=' Gender')
plt.ylabel('Chip Time')
plt.suptitle("")